config/routes.rb
Rails.application.routes.draw do
  resources :accomodations

  root to: "accomodations#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accomodation.rb
class Accomodation < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/accomodations_controller.rb
class AccomodationsController < ApplicationController
  before_action :set_accomodation, only: [:show, :edit, :update, :destroy]

  # GET /accomodations
  # GET /accomodations.json
  def index
    @accomodations = Accomodation.all
  end

  # GET /accomodations/1
  # GET /accomodations/1.json
  def show
  end

  # GET /accomodations/new
  def new
    @accomodation = Accomodation.new
  end

  # GET /accomodations/1/edit
  def edit
  end

  # POST /accomodations
  # POST /accomodations.json
  def create
    @accomodation = Accomodation.new(accomodation_params)

    respond_to do |format|
      if @accomodation.save
        format.html { redirect_to @accomodation, notice: 'Accomodation was successfully created.' }
        format.json { render :show, status: :created, location: @accomodation }
      else
        format.html { render :new }
        format.json { render json: @accomodation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accomodations/1
  # PATCH/PUT /accomodations/1.json
  def update
    respond_to do |format|
      if @accomodation.update(accomodation_params)
        format.html { redirect_to @accomodation, notice: 'Accomodation was successfully updated.' }
        format.json { render :show, status: :ok, location: @accomodation }
      else
        format.html { render :edit }
        format.json { render json: @accomodation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accomodations/1
  # DELETE /accomodations/1.json
  def destroy
    @accomodation.destroy
    respond_to do |format|
      format.html { redirect_to accomodations_url, notice: 'Accomodation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accomodation
      @accomodation = Accomodation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def accomodation_params
      params.require(:accomodation).permit(:title, :body, :city)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/accomodations_helper.rb
module AccomodationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accomodations/_form.html.erb
<%= form_with(model: accomodation, local: true) do |form| %>
  <% if accomodation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(accomodation.errors.count, "error") %> prohibited this accomodation from being saved:</h2>

      <ul>
      <% accomodation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accomodations/edit.html.erb
<h1>Editing Accomodation</h1>

<%= render 'form', accomodation: @accomodation %>

<%= link_to 'Show', @accomodation %> |
<%= link_to 'Back', accomodations_path %>

app/views/accomodations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accomodations</h1>

<% @accomodations.each do |accomodation| %>
<div style="padding:10px; margin-bottom:20px; border:1px solid black">
  <h1><%= accomodation.title %></h1>
  <em><%= accomodation.city %></em>
  <p><%= accomodation.body %></p>
  <%= link_to 'Show', accomodation %>
  <%= link_to 'Edit', edit_accomodation_path(accomodation) %>
  <%= link_to 'Destroy', accomodation, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>
<% end %>

<%= link_to 'New Accomodation', new_accomodation_path %>

app/views/accomodations/new.html.erb
<h1>New Accomodation</h1>

<%= render 'form', accomodation: @accomodation %>

<%= link_to 'Back', accomodations_path %>

app/views/accomodations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @accomodation.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @accomodation.body %>
</p>

<p>
  <strong>City:</strong>
  <%= @accomodation.city %>
</p>

<%= link_to 'Edit', edit_accomodation_path(@accomodation) %> |
<%= link_to 'Back', accomodations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentAPlace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>